In [ ]:
!unzip data_lab5.zip

Archive:  data_lab5.zip
  inflating: data/test_labels.npy    
  inflating: data/test_sentences.npy  
  inflating: data/training_labels.npy  
  inflating: data/training_sentences.npy  


In [ ]:
def normalize_data(train_data, test_data, type=None):
  if type == 'standard':
    scaler = preprocessing.StandardScaler()
    scaler.fit(train_data)
    scaled_train_data = scaler.transform(train_data)
    scaled_test_data = scaler.transform(test_data)

  if type == 'l1':
    scaler = preprocessing.Normalizer(norm='l1')
    scaler.fit(train_data)
    scaled_train_data = scaler.transform(train_data)
    scaled_test_data = scaler.transform(test_data)

  if type == 'l2':
    scaler = preprocessing.Normalizer(norm='l2')
    scaler.fit(train_data)
    scaled_train_data = scaler.transform(train_data)
    scaled_test_data = scaler.transform(test_data)

  else:
    scaled_train_data = train_data
    scaled_test_data = test_data

  return scaled_train_data, scaled_test_data

In [ ]:
 class BagOfWords:

    def __init__(self):
        self.vocabular = {}
        self.cuvinte = []
        self.id = 0

    def build_vocabulary (self, data):
        for eseu in data:
            for cuvant in eseu:
                if cuvant not in self.vocabular.keys():
                    self.vocabular[cuvant] = self.id
                    self.id += 1
                    self.cuvinte.append(cuvant)

    def get_features (self, data):
        features = np.zeros((len(data), self.id))
        # id_sample = -1
        for id_sample, sample in enumerate(data):
            # id_sample += 1
            for word in sample:
                if word in self.vocabular.keys():
                    features[id_sample][self.vocabular[word]] += 1
        return features 

In [ ]:
train_data = np.load('data/training_sentences.npy', allow_pickle=True)
train_labels = np.load('data/training_labels.npy', allow_pickle=True)

test_data = np.load('data/test_sentences.npy', allow_pickle=True)
test_labels = np.load('data/test_labels.npy', allow_pickle=True)

In [ ]:
train_labels

array([0, 0, 1, ..., 0, 0, 0], dtype=int32)

In [ ]:
bow = BagOfWords()
bow.build_vocabulary(train_data)
train = bow.get_features(train_data)
test = bow.get_features(test_data)
normalized_train, normalized_test = normalize_data(train, test, 'l2')

In [ ]:
print(normalized_train)

[[0.35355339 0.35355339 0.35355339 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.19611614 0.19611614 0.        ]
 [0.         0.         0.         ... 0.         0.         0.33333333]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, f1_score


# instantiate SVM
model = SVC(C=1, kernel='linear')
# fit SVM
model.fit(normalized_train, train_labels)
# get predictions SVM
predict = model.predict(normalized_test)
# calculate accuracy/f1
print(accuracy_score(test_labels, predict))
print(f1_score(test_labels, predict))

0.9842391304347826
0.9409368635437881


In [ ]:
model.coef_[0]

array([-0.0120314 , -0.11716947, -0.63366342, ...,  0.        ,
        0.        ,  0.        ])

In [ ]:
idxes = np.argsort(model.coef_[0])

print(idxes.shape)

(9522,)


In [ ]:
print(np.min(model.coef_[0]))
print(model.coef_[0][idxes[0]])

-1.5205706281988167
-1.5205706281988167


In [ ]:
print([bow.cuvinte[i] for i in idxes[:10]])

['&lt#&gt', 'me', 'i', 'Going', 'him', 'Ok', 'I', 'Ill', 'my', 'Im']


In [ ]:
print([bow.cuvinte[i] for i in idxes[-10:]])

['Text', 'To', 'mobile', 'CALL', 'FREE', 'txt', '&', 'Call', 'Txt', 'STOP']


In [ ]:
 class BagOfWords:

    def __init__(self):
        self.vocabular = {}
        self.cuvinte = []
        self.id = 0

    def build_vocabulary(self, data, vocab_size=5000):
        for eseu in data:
            for cuvant in eseu:
                if cuvant not in self.vocabular.keys():
                    self.vocabular[cuvant] = self.id
                    self.id += 1
                    self.cuvinte.append(cuvant)

    def get_features (self, data):
        features = np.zeros((len(data), self.id))
        # id_sample = -1
        for id_sample, sample in enumerate(data):
            # id_sample += 1
            for word in sample:
                if word in self.vocabular.keys():
                    features[id_sample][self.vocabular[word]] += 1
        return features 

In [ ]:
import numpy as np

In [ ]:
train_data = np.load('data/training_sentences.npy', allow_pickle=True)
train_labels = np.load('data/training_labels.npy', allow_pickle=True)

test_data = np.load('data/test_sentences.npy', allow_pickle=True)
test_labels = np.load('data/test_labels.npy', allow_pickle=True)

X_train, y_train = np.load('data/training_sentences.npy', allow_pickle=True), np.load('data/training_labels.npy', allow_pickle=True)
X_test, y_test = np.load('data/test_sentences.npy', allow_pickle=True), np.load('data/test_labels.npy', allow_pickle=True)


print(X_train.shape)
print(X_test.shape)


(3734,)
(1840,)


In [ ]:
import sklearn.preprocessing as preprocessing

#2
def normalize_data(train_data, test_data, type=None):
    if type == 'standard':
        scaler = preprocessing.StandardScaler()
    elif type == 'l1':
        scaler = preprocessing.Normalizer(norm='l1')
    elif type == 'l2':
        scaler = preprocessing.Normalizer(norm='l2')

    if scaler is not None:
        scaler.fit(train_data)
        sc_train = scaler.transform(train_data)
        sc_test = scaler.transform(test_data)
        return sc_train, sc_test
    return train_data, test_data

In [ ]:
def normalize_data(train_data, test_data, type = None):
    n_train_data = train_data
    n_test_data = test_data
    if type == 'standard':
        scaler = preprocessing.StandardScaler()
        scaler.fit(train_data)
        n_train_data = scaler.transform(train_data)
        n_test_data = scaler.transform(test_data)
    elif type == 'l1':
        x_norm = np.sum(abs(train_data), axis = 1)
        n_train_data = train_data/x_norm
        n_test_data = test_data/x_norm
    elif type == 'l2':
        x_norm = np.sqrt(np.sum((train_data ** 2), axis = 1))
        # print(np.sqrt(np.sum((train_data ** 2), axis = 1)).shape)
        # print(train_data.shape)

        # print(np.sqrt(np.sum((test_data ** 2), axis = 1)).shape)
        # print(test_data.shape)
        n_train_data = train_data / np.sqrt(np.sum((train_data ** 2), axis = 1).reshape(3734, 1))
        n_test_data = test_data / np.sqrt(np.sum((test_data ** 2), axis = 1).reshape(1840, 1))
    return n_train_data, n_test_data

normalize_data(X_train, X_test, type='l2')


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: RuntimeWarning: invalid value encountered in true_divide
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in true_divide


(3734, 9522)

In [ ]:
class BagOfWords():
    def __init__(self):
        self.words = []
        self.word_to_id = {}
        
    def build_vocabulary(self, data):
        for sentence in data:
            for word in sentence:
                if word not in self.word_to_id:
                    self.word_to_id[word] = len(self.words)
                    self.words.append(word)
                    
    def get_features(self, data):
        # features = np.array([[0 for _ in range(len(self.words))] for _ in range(len(data))])
        features = np.zeros((len(data), len(self.words)))
        for sentence_id, sentence in enumerate(data):
            for word in sentence:
                if word in self.word_to_id:
                    features[sentence_id][self.word_to_id[word]] += 1
        return features
        
bow = BagOfWords()
bow.build_vocabulary(X_train)
X_train = bow.get_features(X_train)
X_test  = bow.get_features(X_test)

In [ ]:
train_normalised, test_normalised = normalize_data(X_train, X_test, type='l2')

print(train_normalised[0])

[0.08276059 0.08276059 0.99312707 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         

In [ ]:
import sklearn.svm as svm
from sklearn.metrics import accuracy_score, f1_score

vect_class = svm.SVC(C=1, kernel='linear')
vect_class.fit(X_train, train_labels)

test_predict = vect_class.predict(X_test)
print('Accuracy: ', accuracy_score(test_labels, test_predict))

print('F1 score: ', f1_score(test_labels, test_predict))

Accuracy:  0.9847826086956522
F1 score:  0.9423868312757202


In [ ]:
vect_class.coef_.shape

(1, 9522)

In [ ]:
print(np.min(vect_class.coef_))

-0.3916800190214731


In [ ]:
sc = np.argsort(vect_class.coef_)[0]

In [ ]:
print(sc.shape)

(9522,)


In [ ]:
print(sc[0])
print(vect_class.coef_[0, sc[0]])

207
-0.3916800190214731


In [ ]:
top_negative_words = [bow.words[i] for i in sc[:10]]
print(top_negative_words)

# NOT SPAM

['&lt#&gt', 'him', 'Oh', 'Waiting', 'Alright', 'me', 'Lmaonice', 'always', 'It', 'goal']


In [ ]:
top_positive_words = [bow.words[i] for i in sc[-10:]]
print(top_positive_words)

# SPAM

['For', 'Txt', 'widelivecomindex', 'httptms', 'FREE>RingtoneReply', '85233', 'won', 'REAL', 'ringtoneking', '84484']
