In [1]:
!unzip data_lab6.zip

Archive:  data_lab6.zip
  inflating: data/prices.npy         
  inflating: data/training_data.npy  


In [4]:
import numpy as np 
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

# load training data 
training_data = np.load('data/training_data.npy') 
prices = np.load('data/prices.npy') 

# print the first 4 samples 
print('The first 4 samples are:\n ', training_data[:4]) 
print('The first 4 prices are:\n ', prices[:4]) 

# shuffle 
training_data, prices = shuffle(training_data, prices, random_state=0)
X_train, X_test, y_train, y_test = train_test_split(training_data, prices, test_size=0.2, random_state=42)

The first 4 samples are:
  [[2.0150e+03 4.1000e+04 1.9670e+01 1.5820e+03 1.2620e+02 5.0000e+00
  1.0000e+00 0.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  1.0000e+00 0.0000e+00]
 [2.0110e+03 4.6000e+04 1.8200e+01 1.1990e+03 8.8700e+01 5.0000e+00
  1.0000e+00 0.0000e+00 0.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  1.0000e+00 0.0000e+00]
 [2.0120e+03 8.7000e+04 2.0770e+01 1.2480e+03 8.8760e+01 7.0000e+00
  1.0000e+00 0.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  1.0000e+00 0.0000e+00]
 [2.0130e+03 8.6999e+04 2.3080e+01 1.4610e+03 6.3100e+01 5.0000e+00
  1.0000e+00 0.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  1.0000e+00 0.0000e+00]]
The first 4 prices are:
  [12.5  4.5  6.   3.5]


In [5]:
#1 + tipul normalizarii
import sklearn.preprocessing as preprocessing

def normalize_data(train_data, test_data, type='standard'):
    if type == 'standard':
        scaler = preprocessing.StandardScaler()
    elif type == 'minmax':
        scaler = preprocessing.MinMaxScaler()
    
    scaler.fit(train_data)
    sc_train = scaler.transform(train_data)
    sc_test = scaler.transform(test_data)
    return sc_train, sc_test

normalize_data(X_train, X_test, 'minmax')

(array([[0.8571396 , 0.02388206, 0.63380283, ..., 0.        , 1.        ,
         0.        ],
        [0.6666641 , 0.10458039, 0.6161972 , ..., 0.        , 1.        ,
         0.        ],
        [0.7142868 , 0.04529548, 0.7169015 , ..., 0.        , 1.        ,
         0.        ],
        ...,
        [0.7142868 , 0.02789135, 0.7429578 , ..., 0.        , 1.        ,
         0.        ],
        [0.76190186, 0.09561855, 0.68661976, ..., 0.        , 1.        ,
         0.        ],
        [0.6666641 , 0.13451667, 0.671831  , ..., 0.        , 0.        ,
         1.        ]], dtype=float32),
 array([[0.2857132 , 0.27760622, 0.62957746, ..., 0.        , 1.        ,
         0.        ],
        [0.9523773 , 0.04787109, 0.75352114, ..., 0.        , 0.        ,
         1.        ],
        [0.7142868 , 0.07994399, 0.6514085 , ..., 0.        , 1.        ,
         0.        ],
        ...,
        [0.38095093, 0.17619462, 0.45070425, ..., 0.        , 1.        ,
         0.        

In [7]:
#2 + nenormalizat, dar cu 5 fold-uri

from sklearn.metrics import make_scorer, mean_absolute_error, mean_squared_error
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.model_selection import cross_validate

lin_model = LinearRegression()
result = cross_validate(lin_model, X_train, y_train, scoring={
                                'MSE': make_scorer(mean_squared_error),
                                'MAE': make_scorer(mean_absolute_error),
                            },
                         cv=5, n_jobs=-1, verbose=10)
print (np.mean(result['test_MSE']), np.mean(result['test_MAE']))

X_train_norm, X_test_norm = normalize_data(X_train, X_test)

lin_model = LinearRegression()
result = cross_validate(lin_model, X_train_norm, y_train, scoring={
                                'MSE': make_scorer(mean_squared_error),
                                'MAE': make_scorer(mean_absolute_error),
                            },
                         cv=5, n_jobs=-1, verbose=10)

print (np.mean(result['test_MSE']), np.mean(result['test_MAE']))

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.


3.148525333404541 1.317839503288269
3.1485180377960207 1.3178321599960328


[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    0.8s
[Parallel(n_jobs=-1)]: Done   3 out of   5 | elapsed:    0.9s remaining:    0.6s
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    0.9s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    0.9s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Batch computation too fast (0.0104s.) Setting batch_size=2.
[Parallel(n_jobs=-1)]: Done   3 out of   5 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    0.0s finished


In [12]:
#3 + model ridge, lasso + ambele tipuri de normalizari

for method in ["standard","minmax"]:
    for alpha in [1, 10, 100, 1000]:
        X_train_norm, X_test_norm = normalize_data(X_train, X_test, method)

        lin_model = Ridge(alpha)
        result = cross_validate(lin_model, X_train_norm, y_train, scoring={
                                        'MSE': make_scorer(mean_squared_error),
                                        'MAE': make_scorer(mean_absolute_error),
                                    },
                                 cv=5, n_jobs=-1)

        print (method, np.mean(result['test_MSE']), np.mean(result['test_MAE']))

print('---------------------------------------------')

for method in ["standard","minmax"]:
    for alpha in [1, 10, 100, 1000]:
        X_train_norm, X_test_norm = normalize_data(X_train, X_test, method)

        lin_model = Lasso(alpha)
        result = cross_validate(lin_model, X_train_norm, y_train, scoring={
                                        'MSE': make_scorer(mean_squared_error),
                                        'MAE': make_scorer(mean_absolute_error),
                                    },
                                 cv=5, n_jobs=-1)

        print (method, np.mean(result['test_MSE']), np.mean(result['test_MAE']))

standard 3.148504543304443 1.3177947282791138
standard 3.1484719276428224 1.3175026655197144
standard 3.154905080795288 1.3166768312454225
standard 3.43039493560791 1.3688453435897827
minmax 3.1514639377593996 1.3186271429061889
minmax 3.2989612579345704 1.349585270881653
minmax 4.963789939880371 1.7050907135009765
minmax 7.695929431915284 2.177726411819458
---------------------------------------------
standard 6.196308135986328 1.925430965423584
standard 10.457332992553711 2.5277214527130125
standard 10.457332992553711 2.5277214527130125
standard 10.457332992553711 2.5277214527130125
minmax 10.457332992553711 2.5277214527130125
minmax 10.457332992553711 2.5277214527130125
minmax 10.457332992553711 2.5277214527130125
minmax 10.457332992553711 2.5277214527130125


In [14]:
#4 
from sklearn.linear_model import Ridge, Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler, StandardScaler

from itertools import product
from sklearn.model_selection import cross_val_score

pipeline_grid = {
    'scale': [MinMaxScaler(), StandardScaler()],
    'train': [Ridge(), Lasso()],
}
steps = ['scale', 'train']

cv_grid = {
    'train__alpha': [1, 10, 100, 1000]
}

def create_pipelines(pipeline_grid, steps):
    combs = product(*[pipeline_grid[k] for k in steps])
    args = [zip(steps, comb) for comb in combs]
    pipelines = [Pipeline(list(arg)) for arg in args]
    return pipelines

for p in create_pipelines(pipeline_grid, steps):
    res = GridSearchCV(p, param_grid=cv_grid, scoring='neg_mean_squared_error', 
                                cv=3, n_jobs=-1, verbose=0)
    res.fit(X_train, y_train)
    
    print (f"Variant {p}: {res.best_score_} {res.best_params_}")
    model = res.best_estimator_['train']
    print (f"Largetst coef: {np.argmax(model.coef_)}")
    print (f"Smallest coef: {np.argmin(model.coef_)}")
    
    cnt_0 = len([x for x in model.coef_ if x < 1e-3])
    print (f"Zero coefs: {cnt_0}")

Variant Pipeline(memory=None,
         steps=[('scale', MinMaxScaler(copy=True, feature_range=(0, 1))),
                ('train',
                 Ridge(alpha=1.0, copy_X=True, fit_intercept=True,
                       max_iter=None, normalize=False, random_state=None,
                       solver='auto', tol=0.001))],
         verbose=False): -3.170071601867676 {'train__alpha': 1}
Largetst coef: 4
Smallest coef: 2
Zero coefs: 8
Variant Pipeline(memory=None,
         steps=[('scale', MinMaxScaler(copy=True, feature_range=(0, 1))),
                ('train',
                 Lasso(alpha=1.0, copy_X=True, fit_intercept=True,
                       max_iter=1000, normalize=False, positive=False,
                       precompute=False, random_state=None, selection='cyclic',
                       tol=0.0001, warm_start=False))],
         verbose=False): -10.455515225728353 {'train__alpha': 1}
Largetst coef: 0
Smallest coef: 0
Zero coefs: 14
Variant Pipeline(memory=None,
         steps=[(