In [ ]:
!unzip ai-unibuc-24-22-2021.zip

In [22]:
from sklearn.naive_bayes import MultinomialNB
import sklearn.datasets as datasets
import numpy as np
from PIL import Image
from matplotlib import image, pyplot

In [5]:
print('Pillow Version:', PIL.__version__)

Pillow Version: 7.0.0


In [ ]:
#image = Image.open("train/000000.png")

#print(image.format)
#print(image.size)
#print(image.mode)

image = Image.open("train/000000.png")
data = np.asarray(image)
print(type(data))
print(data.shape)

fin = open("train.txt")
train = fin.read().split("\n")
fin.close()
print(train)

ok = 0
for i in range(len(train)):
  train[i] = train[i].split(",")
del train[-1]


train_images = np.array([])
train_labels = np.array([])

for x in train:
  print(x[0])
  image = Image.open("train/" + x[0])
  img = np.asarray(image)
  train_images = np.append(train_images, img)
  train_labels = np.append(train_labels, x[1])




In [107]:
print(train_images.shape)
print(train_labels.shape)

train_images = train_images.reshape(30001,1024)
train_labels = train_labels.astype(np.int)

print(train_images.shape)
print(train_labels.shape)

(30001, 1024)
(30001,)
(30001, 1024)
(30001,)


In [112]:
fin = open("validation.txt")
validation = fin.read().split("\n")
for i in range(len(validation)):
  validation[i] = validation[i].split(",")
del validation[-1]

validation_images = np.array([])
validation_labels = np.array([])

for x in validation:
  print(x[0])
  image = Image.open("validation/" + x[0])
  img = np.asarray(image)
  #print(img)
  validation_images = np.append(validation_images, img)
  validation_labels = np.append(validation_labels, x[1])

validation_labels = validation_labels.astype(np.int)
print(validation_images.shape)

Streaming output truncated to the last 5000 lines.
030002.png
030003.png
030004.png
030005.png
030006.png
030007.png
030008.png
030009.png
030010.png
030011.png
030012.png
030013.png
030014.png
030015.png
030016.png
030017.png
030018.png
030019.png
030020.png
030021.png
030022.png
030023.png
030024.png
030025.png
030026.png
030027.png
030028.png
030029.png
030030.png
030031.png
030032.png
030033.png
030034.png
030035.png
030036.png
030037.png
030038.png
030039.png
030040.png
030041.png
030042.png
030043.png
030044.png
030045.png
030046.png
030047.png
030048.png
030049.png
030050.png
030051.png
030052.png
030053.png
030054.png
030055.png
030056.png
030057.png
030058.png
030059.png
030060.png
030061.png
030062.png
030063.png
030064.png
030065.png
030066.png
030067.png
030068.png
030069.png
030070.png
030071.png
030072.png
030073.png
030074.png
030075.png
030076.png
030077.png
030078.png
030079.png
030080.png
030081.png
030082.png
030083.png
030084.png
030085.png
030086.png
030087.png
030

In [147]:
validation_images = validation_images.reshape(5000,1024)
print(validation_images.shape)

(5000, 1024)


In [125]:
num_bins = 2
bins = np.linspace(start=0, stop=255, num=num_bins)

print(bins)

def values_to_bins(x, bins):
    x_to_bins = np.digitize(x, bins)
    return x_to_bins - 1

x_train = values_to_bins(train_images, bins)
x_test = values_to_bins(validation_images, bins)

print(x_train.min())
print(x_train.max())

[  0. 255.]
0
1


In [155]:
num_bins = 12
bins = np.linspace(start=0, stop=255, num=num_bins)

x_train = values_to_bins(train_images, bins)
x_test = values_to_bins(validation_images, bins)

naive_bayes_model = MultinomialNB()
naive_bayes_model.fit(x_train, train_labels)


p = naive_bayes_model.predict(x_test)
accuracy = naive_bayes_model.score(x_test, validation_labels)

print(accuracy)
print(p.shape)
print(x_test)

0.392
(5000,)
[[ 2  2  2 ...  1  2  1]
 [ 6  7  7 ...  6  6  6]
 [ 0  0  0 ...  4  4  4]
 ...
 [ 7  8  8 ...  8  9 10]
 [ 9  9  9 ... 10 10  8]
 [11 11 11 ... 11 11 11]]


In [175]:
fin = open("test.txt")
test = fin.read().split("\n")
del test[-1]
print(test)

test_images = np.array([])

for x in test:
  print(x)
  image = Image.open("test/" + x)
  img = np.asarray(image)
  #print(img)
  test_images = np.append(test_images, img)

print(test_images.shape)

Streaming output truncated to the last 5000 lines.
035002.png
035003.png
035004.png
035005.png
035006.png
035007.png
035008.png
035009.png
035010.png
035011.png
035012.png
035013.png
035014.png
035015.png
035016.png
035017.png
035018.png
035019.png
035020.png
035021.png
035022.png
035023.png
035024.png
035025.png
035026.png
035027.png
035028.png
035029.png
035030.png
035031.png
035032.png
035033.png
035034.png
035035.png
035036.png
035037.png
035038.png
035039.png
035040.png
035041.png
035042.png
035043.png
035044.png
035045.png
035046.png
035047.png
035048.png
035049.png
035050.png
035051.png
035052.png
035053.png
035054.png
035055.png
035056.png
035057.png
035058.png
035059.png
035060.png
035061.png
035062.png
035063.png
035064.png
035065.png
035066.png
035067.png
035068.png
035069.png
035070.png
035071.png
035072.png
035073.png
035074.png
035075.png
035076.png
035077.png
035078.png
035079.png
035080.png
035081.png
035082.png
035083.png
035084.png
035085.png
035086.png
035087.png
035

In [176]:
test_images = test_images.reshape(5000,1024)
print(test_images.shape)


(5000, 1024)


In [177]:
num_bins = 12
bins = np.linspace(start=0, stop=255, num=num_bins)

x_train = values_to_bins(train_images, bins)
x_test = values_to_bins(test_images, bins)

naive_bayes_model = MultinomialNB()
naive_bayes_model.fit(x_train, train_labels)


p = naive_bayes_model.predict(x_test)


(5000,)


In [199]:
print(p.shape)
fout = open("prediction.csv", "w")
i = 0
fout.write("id,label" + "\n")
for x in p:
  fout.write(test[i] + "," + str(x) + "\n")
  i += 1

print(p[i - 3])

(5000,)
7
