In [1]:
!unzip ai-unibuc-24-22-2021.zip

Streaming output truncated to the last 5000 lines.
  inflating: validation/030001.png   
  inflating: validation/030002.png   
  inflating: validation/030003.png   
  inflating: validation/030004.png   
  inflating: validation/030005.png   
  inflating: validation/030006.png   
  inflating: validation/030007.png   
  inflating: validation/030008.png   
  inflating: validation/030009.png   
  inflating: validation/030010.png   
  inflating: validation/030011.png   
  inflating: validation/030012.png   
  inflating: validation/030013.png   
  inflating: validation/030014.png   
  inflating: validation/030015.png   
  inflating: validation/030016.png   
  inflating: validation/030017.png   
  inflating: validation/030018.png   
  inflating: validation/030019.png   
  inflating: validation/030020.png   
  inflating: validation/030021.png   
  inflating: validation/030022.png   
  inflating: validation/030023.png   
  inflating: validation/030024.png   
  inflating: validation/030025.png   

In [4]:
from sklearn.naive_bayes import MultinomialNB
import sklearn.datasets as datasets
import numpy as np
from PIL import Image
from matplotlib import image, pyplot

In [5]:
print('Pillow Version:', PIL.__version__)

NameError: ignored

In [6]:
#image = Image.open("train/000000.png")

#print(image.format)
#print(image.size)
#print(image.mode)

image = Image.open("train/000000.png")
data = np.asarray(image)
print(type(data))
print(data.shape)

fin = open("train.txt")
train = fin.read().split("\n")
fin.close()
print(train)

ok = 0
for i in range(len(train)):
  train[i] = train[i].split(",")
del train[-1] # "\n"


train_images = np.array([])
train_labels = np.array([])

for x in train:
  print(x[0])
  image = Image.open("train/" + x[0])
  img = np.asarray(image)
  train_images = np.append(train_images, img)
  train_labels = np.append(train_labels, x[1])




Streaming output truncated to the last 5000 lines.
025001.png
025002.png
025003.png
025004.png
025005.png
025006.png
025007.png
025008.png
025009.png
025010.png
025011.png
025012.png
025013.png
025014.png
025015.png
025016.png
025017.png
025018.png
025019.png
025020.png
025021.png
025022.png
025023.png
025024.png
025025.png
025026.png
025027.png
025028.png
025029.png
025030.png
025031.png
025032.png
025033.png
025034.png
025035.png
025036.png
025037.png
025038.png
025039.png
025040.png
025041.png
025042.png
025043.png
025044.png
025045.png
025046.png
025047.png
025048.png
025049.png
025050.png
025051.png
025052.png
025053.png
025054.png
025055.png
025056.png
025057.png
025058.png
025059.png
025060.png
025061.png
025062.png
025063.png
025064.png
025065.png
025066.png
025067.png
025068.png
025069.png
025070.png
025071.png
025072.png
025073.png
025074.png
025075.png
025076.png
025077.png
025078.png
025079.png
025080.png
025081.png
025082.png
025083.png
025084.png
025085.png
025086.png
025

In [7]:
print(train_images.shape)
print(train_labels.shape)

train_images = train_images.reshape(30001,1024)
train_labels = train_labels.astype(np.int)

print(train_images.shape)
print(train_labels.shape)

(30721024,)
(30001,)
(30001, 1024)
(30001,)


In [8]:
fin = open("validation.txt")
validation = fin.read().split("\n")
for i in range(len(validation)):
  validation[i] = validation[i].split(",")
del validation[-1] # "\n"

validation_images = np.array([])
validation_labels = np.array([])

for x in validation:
  print(x[0])
  image = Image.open("validation/" + x[0])
  img = np.asarray(image)
  #print(img)
  validation_images = np.append(validation_images, img)
  validation_labels = np.append(validation_labels, x[1])

validation_labels = validation_labels.astype(np.int)
print(validation_images.shape)

Streaming output truncated to the last 5000 lines.
030002.png
030003.png
030004.png
030005.png
030006.png
030007.png
030008.png
030009.png
030010.png
030011.png
030012.png
030013.png
030014.png
030015.png
030016.png
030017.png
030018.png
030019.png
030020.png
030021.png
030022.png
030023.png
030024.png
030025.png
030026.png
030027.png
030028.png
030029.png
030030.png
030031.png
030032.png
030033.png
030034.png
030035.png
030036.png
030037.png
030038.png
030039.png
030040.png
030041.png
030042.png
030043.png
030044.png
030045.png
030046.png
030047.png
030048.png
030049.png
030050.png
030051.png
030052.png
030053.png
030054.png
030055.png
030056.png
030057.png
030058.png
030059.png
030060.png
030061.png
030062.png
030063.png
030064.png
030065.png
030066.png
030067.png
030068.png
030069.png
030070.png
030071.png
030072.png
030073.png
030074.png
030075.png
030076.png
030077.png
030078.png
030079.png
030080.png
030081.png
030082.png
030083.png
030084.png
030085.png
030086.png
030087.png
030

In [9]:
validation_images = validation_images.reshape(5000,1024)
print(validation_images.shape)

(5000, 1024)


In [ ]:
#NAIVE BAYES

In [ ]:
num_bins = 2
bins = np.linspace(start=0, stop=255, num=num_bins)

print(bins)

def values_to_bins(x, bins):
    x_to_bins = np.digitize(x, bins)
    return x_to_bins - 1

x_train = values_to_bins(train_images, bins)
x_test = values_to_bins(validation_images, bins)

print(x_train.min())
print(x_train.max())

[  0. 255.]
0
1


In [ ]:
num_bins = 12
bins = np.linspace(start=0, stop=255, num=num_bins)

x_train = values_to_bins(train_images, bins)
x_test = values_to_bins(validation_images, bins)

naive_bayes_model = MultinomialNB()
naive_bayes_model.fit(x_train, train_labels)


p = naive_bayes_model.predict(x_test)
accuracy = naive_bayes_model.score(x_test, validation_labels)

print(accuracy)
print(p.shape)
print(x_test)

0.392
(5000,)
[[ 2  2  2 ...  1  2  1]
 [ 6  7  7 ...  6  6  6]
 [ 0  0  0 ...  4  4  4]
 ...
 [ 7  8  8 ...  8  9 10]
 [ 9  9  9 ... 10 10  8]
 [11 11 11 ... 11 11 11]]


In [ ]:
fin = open("test.txt")
test = fin.read().split("\n")
del test[-1]
print(test)

test_images = np.array([])

for x in test:
  print(x)
  image = Image.open("test/" + x)
  img = np.asarray(image)
  #print(img)
  test_images = np.append(test_images, img)

print(test_images.shape)

Streaming output truncated to the last 5000 lines.
035002.png
035003.png
035004.png
035005.png
035006.png
035007.png
035008.png
035009.png
035010.png
035011.png
035012.png
035013.png
035014.png
035015.png
035016.png
035017.png
035018.png
035019.png
035020.png
035021.png
035022.png
035023.png
035024.png
035025.png
035026.png
035027.png
035028.png
035029.png
035030.png
035031.png
035032.png
035033.png
035034.png
035035.png
035036.png
035037.png
035038.png
035039.png
035040.png
035041.png
035042.png
035043.png
035044.png
035045.png
035046.png
035047.png
035048.png
035049.png
035050.png
035051.png
035052.png
035053.png
035054.png
035055.png
035056.png
035057.png
035058.png
035059.png
035060.png
035061.png
035062.png
035063.png
035064.png
035065.png
035066.png
035067.png
035068.png
035069.png
035070.png
035071.png
035072.png
035073.png
035074.png
035075.png
035076.png
035077.png
035078.png
035079.png
035080.png
035081.png
035082.png
035083.png
035084.png
035085.png
035086.png
035087.png
035

In [ ]:
test_images = test_images.reshape(5000,1024)
print(test_images.shape)


(5000, 1024)


In [ ]:
num_bins = 12
bins = np.linspace(start=0, stop=255, num=num_bins)

x_train = values_to_bins(train_images, bins)
x_test = values_to_bins(test_images, bins)

naive_bayes_model = MultinomialNB()
naive_bayes_model.fit(x_train, train_labels)


p = naive_bayes_model.predict(x_test)


(5000,)


In [ ]:
print(p.shape)
fout = open("prediction.csv", "w")
i = 0
fout.write("id,label" + "\n")
for x in p:
  fout.write(test[i] + "," + str(x) + "\n")
  i += 1

print(p[i - 3])

(5000,)
7


In [ ]:
#PERCEPTRON

In [87]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X2 = scaler.fit_transform(train_images)

X2_test = scaler.transform(validation_images)

y2 = train_labels
y2_test = validation_labels


X_train_scaled = scaler.transform(train_images)
X_test_scaled = scaler.transform(validation_images)

print(X_test_scaled.shape)

(5000, 1024)


In [12]:
from sklearn.neural_network import MLPClassifier

mlp_classifier_model = MLPClassifier(activation='tanh', hidden_layer_sizes=(1), learning_rate_init=0.0001, momentum=0, max_iter=200)
mlp_classifier_model.fit(X2, y2)
predict = mlp_classifier_model.predict(X2_test)

from sklearn.metrics import accuracy_score

acc = accuracy_score(predict, y2_test)
print(acc) 

0.2306


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [13]:
mlp_classifier_model = MLPClassifier(activation='tanh', hidden_layer_sizes=(10),
                        learning_rate_init=0.01, momentum=0, max_iter=200)

mlp_classifier_model.fit(X2, y2)
predict = mlp_classifier_model.predict(X2_test)

from sklearn.metrics import accuracy_score

acc = accuracy_score(predict, y2_test)
print(acc) 

0.5208


In [ ]:
# c
mlp_classifier_model = MLPClassifier(activation='tanh',hidden_layer_sizes=(10),
            learning_rate_init=0.00001, momentum=0, max_iter=200)
mlp_classifier_model.fit(X2, y2)
predict = mlp_classifier_model.predict(X2_test)

from sklearn.metrics import accuracy_score

acc = accuracy_score(predict, y2_test)
print(acc)

In [14]:
clf = MLPClassifier(activation='relu', hidden_layer_sizes=(100, 100),
                    learning_rate_init=0.01, momentum=0,
                    max_iter=2000)

clf.fit(X2, y2)
print(clf.score(X2, y2))
print(clf.score(X2_test, y2_test))

0.8052064931168961
0.6774


In [15]:
clf = MLPClassifier(activation='relu', hidden_layer_sizes=(100, 100),
                    learning_rate_init=0.01, momentum=0,
                    max_iter=5000)

clf.fit(X2, y2)
print(clf.score(X2, y2))
print(clf.score(X2_test, y2_test))

0.8172727575747475
0.6928


In [16]:
clf = MLPClassifier(activation='relu', hidden_layer_sizes=(100, 100),
                    learning_rate_init=0.01, momentum=0,
                    max_iter=5000)

clf.fit(X2, y2)
print(clf.score(X2, y2))
print(clf.score(X2_test, y2_test))

0.6090130328989034
0.5908


In [69]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import regularizers

inputs = tf.keras.Input(shape=(32, 32, 1))

#x = layers.Conv2D(filters=32, kernel_size=(3, 3), activation="relu", padding="same")(inputs)
x = layers.Conv2D(filters=16, kernel_size=(3, 3), padding="same", activation="relu", use_bias=True, bias_regularizer=regularizers.l2(1e-3))(inputs)
#x = layers.Dropout(0.4)(x)
x = layers.MaxPooling2D()(x)
x = layers.Conv2D(filters=32, kernel_size=(3, 3), padding="same", activation="relu", use_bias=True, bias_regularizer=regularizers.l2(1e-3))(x)
#x = layers.Dropout(0.4)(x)
x = layers.MaxPooling2D(pool_size=(2, 2))(x)
x = layers.Conv2D(filters=64, kernel_size=(3, 3), padding="same", activation="relu", use_bias=True, bias_regularizer=regularizers.l2(1e-3))(x)
x = layers.Dropout(0.4)(x)

# x = layers.GlobalAveragePooling2D()(x)
x = layers.Flatten()(x)

outputs = layers.Dense(10, activation='softmax')(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

model.summary()

Model: "model_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         [(None, 32, 32, 1)]       0         
_________________________________________________________________
conv2d_21 (Conv2D)           (None, 32, 32, 16)        160       
_________________________________________________________________
max_pooling2d_14 (MaxPooling (None, 16, 16, 16)        0         
_________________________________________________________________
conv2d_22 (Conv2D)           (None, 16, 16, 32)        4640      
_________________________________________________________________
max_pooling2d_15 (MaxPooling (None, 8, 8, 32)          0         
_________________________________________________________________
conv2d_23 (Conv2D)           (None, 8, 8, 64)          18496     
_________________________________________________________________
dropout_10 (Dropout)         (None, 8, 8, 64)          0   

In [70]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=3e-4), loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='accuracy')

In [88]:
model.fit(X_train_scaled.reshape(-1, 32, 32, 1), train_labels, batch_size=64, epochs=32, validation_data=(X_test_scaled.reshape(-1, 32, 32, 1), validation_labels),shuffle=True)

Epoch 1/32
469/469 [==============================] - 34s 73ms/step - loss: 0.2803 - accuracy: 0.8982 - val_loss: 0.4123 - val_accuracy: 0.8550
Epoch 2/32
469/469 [==============================] - 35s 75ms/step - loss: 0.2709 - accuracy: 0.9013 - val_loss: 0.4124 - val_accuracy: 0.8614
Epoch 3/32
469/469 [==============================] - 34s 73ms/step - loss: 0.2682 - accuracy: 0.9026 - val_loss: 0.4067 - val_accuracy: 0.8636
Epoch 4/32
469/469 [==============================] - 34s 73ms/step - loss: 0.2627 - accuracy: 0.9052 - val_loss: 0.4135 - val_accuracy: 0.8612
Epoch 5/32
469/469 [==============================] - 34s 72ms/step - loss: 0.2584 - accuracy: 0.9077 - val_loss: 0.4165 - val_accuracy: 0.8586
Epoch 6/32
469/469 [==============================] - 34s 72ms/step - loss: 0.2525 - accuracy: 0.9090 - val_loss: 0.4066 - val_accuracy: 0.8636
Epoch 7/32
469/469 [==============================] - 34s 72ms/step - loss: 0.2493 - accuracy: 0.9107 - val_loss: 0.4194 - val_accuracy:

In [84]:
model.evaluate(X_test_scaled.reshape(-1, 32, 32, 1), validation_labels)

157/157 [==============================] - 2s 12ms/step - loss: 0.4187 - accuracy: 0.8632


[0.4187276363372803, 0.8632000088691711]

In [56]:
import tensorflow as tf
from tensorflow.keras import layers

inputs1 = tf.keras.Input(shape=(None, 1024))

x1 = layers.Dense(10, activation='relu')(inputs1)
x1 = layers.Dropout(0.2)(x1)
x1 = layers.Dense(10, activation='relu')(x1)

outputs1 = layers.Dense(10, activation='softmax')(x1)

model1 = tf.keras.Model(inputs=inputs1, outputs=outputs1)

model1.summary()

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, None, 1024)]      0         
_________________________________________________________________
dense_4 (Dense)              (None, None, 10)          10250     
_________________________________________________________________
dropout_6 (Dropout)          (None, None, 10)          0         
_________________________________________________________________
dense_5 (Dense)              (None, None, 10)          110       
_________________________________________________________________
dense_6 (Dense)              (None, None, 10)          110       
Total params: 10,470
Trainable params: 10,470
Non-trainable params: 0
_________________________________________________________________


In [57]:
model1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=3e-3), loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='accuracy')

In [61]:
model1.fit(X_train_scaled, train_labels, batch_size=32, epochs=64, validation_data=(X_test_scaled, validation_labels), shuffle=True)

Epoch 1/64
938/938 [==============================] - 3s 3ms/step - loss: 1.8399 - accuracy: 0.3501 - val_loss: 1.3677 - val_accuracy: 0.5320
Epoch 2/64
938/938 [==============================] - 2s 3ms/step - loss: 1.4891 - accuracy: 0.4700 - val_loss: 1.2878 - val_accuracy: 0.5574
Epoch 3/64
938/938 [==============================] - 2s 3ms/step - loss: 1.4378 - accuracy: 0.4939 - val_loss: 1.2771 - val_accuracy: 0.5656
Epoch 4/64
938/938 [==============================] - 2s 3ms/step - loss: 1.4148 - accuracy: 0.5036 - val_loss: 1.2526 - val_accuracy: 0.5758
Epoch 5/64
938/938 [==============================] - 2s 2ms/step - loss: 1.3965 - accuracy: 0.5110 - val_loss: 1.2417 - val_accuracy: 0.5786
Epoch 6/64
938/938 [==============================] - 2s 2ms/step - loss: 1.3731 - accuracy: 0.5219 - val_loss: 1.2353 - val_accuracy: 0.5886
Epoch 7/64
938/938 [==============================] - 2s 3ms/step - loss: 1.3762 - accuracy: 0.5244 - val_loss: 1.2193 - val_accuracy: 0.5882
Epoch 

In [50]:
fin = open("test.txt")
test = fin.read().split("\n")
del test[-1]
print(test)

test_images = np.array([])

for x in test:
  print(x)
  image = Image.open("test/" + x)
  img = np.asarray(image)
  #print(img)
  test_images = np.append(test_images, img)

print(test_images.shape)
test_images = test_images.reshape(5000,1024)
print(test_images.shape)

Streaming output truncated to the last 5000 lines.
035003.png
035004.png
035005.png
035006.png
035007.png
035008.png
035009.png
035010.png
035011.png
035012.png
035013.png
035014.png
035015.png
035016.png
035017.png
035018.png
035019.png
035020.png
035021.png
035022.png
035023.png
035024.png
035025.png
035026.png
035027.png
035028.png
035029.png
035030.png
035031.png
035032.png
035033.png
035034.png
035035.png
035036.png
035037.png
035038.png
035039.png
035040.png
035041.png
035042.png
035043.png
035044.png
035045.png
035046.png
035047.png
035048.png
035049.png
035050.png
035051.png
035052.png
035053.png
035054.png
035055.png
035056.png
035057.png
035058.png
035059.png
035060.png
035061.png
035062.png
035063.png
035064.png
035065.png
035066.png
035067.png
035068.png
035069.png
035070.png
035071.png
035072.png
035073.png
035074.png
035075.png
035076.png
035077.png
035078.png
035079.png
035080.png
035081.png
035082.png
035083.png
035084.png
035085.png
035086.png
035087.png
035088.png
035

In [89]:
X_test_scaled = scaler.transform(test_images)
print(X_test_scaled.shape)

(5000, 1024)


In [90]:
predictions = model.predict(X_test_scaled.reshape(-1, 32, 32, 1), batch_size=64)
print(predictions)

[[2.16759872e-05 2.89158155e-08 3.78760001e-06 ... 5.27046574e-03
  3.19941336e-08 3.80091159e-16]
 [7.52159059e-01 2.86184095e-05 6.44434840e-06 ... 2.90183124e-07
  7.04346178e-07 2.69178653e-16]
 [3.23645584e-03 9.26096320e-01 2.12054001e-03 ... 4.18408923e-02
  4.61113779e-03 5.93680400e-12]
 ...
 [6.38649135e-06 6.75445735e-01 3.01625997e-01 ... 5.43149048e-03
  1.06580675e-10 2.25270496e-14]
 [3.98996115e-01 1.16364739e-03 9.77853779e-06 ... 4.74697977e-01
  3.93601274e-03 6.17711715e-10]
 [4.92666692e-01 4.29795671e-10 8.24332312e-02 ... 5.65489405e-04
  7.92168350e-07 5.91535111e-12]]


In [91]:
predictions = model.predict(X_test_scaled.reshape(-1, 32, 32, 1), batch_size=64)
fout = open("prediction.csv", "w")
i = 0
fout.write("id,label" + "\n")
for x in predictions:
  y = np.argmax(x)
  fout.write(test[i] + "," + str(y) + "\n")
  i += 1

fout.close()